
export const GET_PROMOTED_COINS = 'GET_PROMOTED_COINS';
export const GET_PROMOTED_COINS_SUCCESS = 'GET_PROMOTED_COINS_SUCCESS';
export const GET_PROMOTED_COINS_FAILURE = 'GET_PROMOTED_COINS_FAILURE';

export const ADD_COINS = 'ADD_COINS';
export const ADD_COINS_SUCCESS = 'ADD_COINS_SUCCESS';
export const ADD_COINS_FAILURE = 'ADD_COINS_FAILURE';

export const UPDATE_COINS = 'UPDATE_COINS';
export const UPDATE_COINS_SUCCESS = 'UPDATE_COINS_SUCCESS';
export const UPDATE_COINS_FAILURE = 'UPDATE_COINS_FAILURE';

export const VOTE_COINS = 'ADD_COINS';
export const VOTE_COINS_SUCCESS = 'ADD_COINS_SUCCESS';
export const VOTE_COINS_FAILURE = 'ADD_COINS_FAILURE';

export const COIN_TYPE_PROMOTED='P';
export const COIN_TYPE_ATB='ATB';
export const COIN_TYPE_NORMAL='NOR';
export const COIN_TYPE_NEW='NEW';
export const COIN_TYPE_PRE_SALE='PRE';

export const POPULATE_COINS_DETAILS = 'POPULATE_COINS_DETAILS';